import {
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  Bell,
  Check,
  ChevronLeft,
  ChevronRight,
  CircleEllipsis,
  Download,
  Eye,
  EyeOff,
  GripVertical,
  Heart,
  Home,
  ListMusic,
  LogOut,
  MoreHorizontal,
  Music2,
  Pencil,
  Plus,
  Search,
  Send,
  Star,
  Trash2,
  UserRound,
  UsersRound,
  X,
} from "lucide-react";

const ICONS = {
  "arrow-down": ArrowDown,
  "arrow-left": ArrowLeft,
  "arrow-right": ArrowRight,
  "arrow-up": ArrowUp,
  bell: Bell,
  check: Check,
  "chevron-left": ChevronLeft,
  "chevron-right": ChevronRight,
  ellipsis: CircleEllipsis,
  download: Download,
  eye: Eye,
  "eye-off": EyeOff,
  grip: GripVertical,
  heart: Heart,
  home: Home,
  list: ListMusic,
  logout: LogOut,
  more: MoreHorizontal,
  music: Music2,
  pencil: Pencil,
  plus: Plus,
  search: Search,
  send: Send,
  star: Star,
  trash: Trash2,
  user: UserRound,
  users: UsersRound,
  x: X,
};

export default function AppIcon({ name, size = 18, label, ...props }) {
  const Icon = ICONS[name];
  if (!Icon) return null;
  return <Icon className="app-icon" size={size} strokeWidth={1.8} role={label ? "img" : undefined} aria-hidden={label ? undefined : true} aria-label={label} focusable="false" {...props} />;
}
